version: '3'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    build: otrs
    ports:
      - '80:80'
    # If running behind a proxy container, expose the ports instead
    # and link the proxy container to this one.
    #  expose:
    #  - "80"
    links:
      - mariadb:mariadb
      - postfix:postfix
    #Put all environment variables in otrs-setup.env file
    env_file: otrs-setup.env
    volumes:
      - './volumes/config:/opt/otrs/Kernel'
      - './otrs/backup:/var/otrs/backups'
      - '/etc/localtime:/etc/localtime:ro'
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    build: mariadb
    expose:
      - "3306"
    env_file: otrs-setup.env
    volumes:
      - './volumes/mysql:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
  postfix:
    image: juanluisbaptiste/postfix:latest
    expose:
      - '25'
    env_file: credentials-smtp.env
